version: '2'
services:
  code:
    image: debian:jessie
    volumes:
      - ../:/var/www

  mysqldata:
    image: debian:jessie
    volumes:
      - ./mysql/data:/var/lib/mysql

  nginx:
    build: ./nginx
    environment:
      - SERVER_NAME=localhost
      - MAGE_ROOT=/var/www
      - MAGE_MODE=developer
    volumes_from:
      - code
    volumes:
      - ./nginx/logs:/var/log/nginx/test
    links:
      - php:fpm
    ports:
      - "81:80"

  php:
    build: ./php
    image: nixteam/php:7.0.10-dev
    environment:
      - TERM=xtermgit
      - DEVELOPER_HOST=172.20.1.1
      - DEVELOPER_PORT=9000
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=test
    volumes_from:
      - code
    links:
      - mysql

  mysql:
    image: mysql:5.7.15
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes_from:
      - mysqldata
    ports:
      - "33061:3306"

  cron:
    build: ./cron
    depends_on:
      - php
    environment:
      - TERM=xterm
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testpass
    volumes_from:
      - code
    links:
      - mysql